name: ThalwyrnResources
version: '${project.version}'
main: com.pro4d.thalwyrnresources.ThalwyrnResources
api-version: 1.18
load: STARTUP
depend: [ MMOCore ]
softdepend: [ MMOItems, WorldGuard, WorldEdit ]
authors: [ Pro4D ]
description: Spawn and configure resource deposits! 

commands:
  resource: